[build]
command = "pnpm build"
publish = "build"

[build.environment]
NODE_VERSION = "18.9.0"

[[redirects]]
force = true
from = "https://ocean-artup.netlify.com/*"
to = "https://ocean-artup.eu/:splat"
