[build]
command = "yarn build"
publish = "build"

[build.environment]
NODE_VERSION = "17.0.1"
YARN_VERSION = "1.22.11"

[[redirects]]
force = true
from = "https://ocean-artup.netlify.com/*"
to = "https://ocean-artup.eu/:splat"
