[build]
command = "yarn build"
publish = "build"

[build.environment]
NODE_VERSION = "16.1.0"
YARN_VERSION = "1.22.10"

[[redirects]]
force = true
from = "https://ocean-artup.netlify.com/*"
to = "https://ocean-artup.eu/:splat"
