[build]
  command = "yarn export"
  publish = "__sapper__/export"

[build.environment]
  NODE_VERSION = "15.5.0"
  YARN_VERSION = "1.22.10"

[[redirects]]
  from = "https://ocean-artup.netlify.com/*"
  to = "https://ocean-artup.eu/:splat"
  force = true
