name: Lighthouse

on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm add @lhci/cli

      - name: Build site
        run: pnpm build
        env:
          VITE_CONTENTFUL_SPACE_ID: ${{ secrets.VITE_CONTENTFUL_SPACE_ID }}
          VITE_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.VITE_CONTENTFUL_ACCESS_TOKEN }}
          # to prevent penalty 'Browser errors were logged to the console' from
          # 'Invalid appId: undefined' in Lighthouse CI
          VITE_ALGOLIA_APP_ID: ${{ secrets.VITE_ALGOLIA_APP_ID }}
          VITE_ALGOLIA_SEARCH_KEY: ${{ secrets.VITE_ALGOLIA_SEARCH_KEY }}

      - name: Run Lighthouse
        run: pnpm lhci autorun
        # configure https://github.com/apps/lighthouse-ci for this repo
        # to display Lighthouse results below PRs
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
